module.exports.decks = {
  'items': [
    {name: 'револьвер 38-го калибра', src: 'statics/items/38_revolver.jpg', type: ['item', 'weapon']},
    {name: 'пистолет 45-го калибра', src: 'statics/items/45_caliber_pistol.jpg', type: ['item', 'weapon']},
    {name: 'обращение к совету', src: 'statics/items/advice.jpg', type: ['service']},
    {name: 'бинты', src: 'statics/items/bandages.jpg', type: ['item']},
    {name: 'телохранитель', src: 'statics/items/bodyguard.jpg', type: ['ally']},
    {name: 'книга тайн', src: 'statics/items/book_of_secrets.jpg', type: ['item', 'book']},
    {name: 'карабин', src: 'statics/items/carabiner.jpg', type: ['item', 'weapon']},
    {name: 'чартерный рейс', src: 'statics/items/charter_flight.jpg', type: ['service']},
    {name: 'городской гид', src: 'statics/items/city_guide.jpg', type: ['ally']},
    {name: 'кольт 45-го калибра', src: 'statics/items/colt_45.jpg', type: ['item', 'weapon']},
    {name: 'посвящение', src: 'statics/items/consecration.jpg', type: ['service']},
    {name: 'конспиролог', src: 'statics/items/conspiracy_researcher.jpg', type: ['ally']},
    {name: 'крест', src: 'statics/items/cross.jpg', type: ['item']},
    {name: 'наручники', src: 'statics/items/cuffs.jpg', type: ['item']},
    {name: 'кинжал душ', src: 'statics/items/dagger_of_souls.jpg', type: ['item', 'magic', 'weapon']},
    {name: 'наёмная чародейка', src: 'statics/items/dedicated_mercenary.jpg', type: ['ally']},
    {name: '"дерринджер" 18-го калибра', src: 'statics/items/derringer.jpg', type: ['trinket', 'weapon']},
    {name: 'двуствольный дробовик', src: 'statics/items/double_barrel_shotgun.jpg', type: ['item', 'weapon']},
    {name: 'динамит', src: 'statics/items/dynamite.jpg', type: ['item', 'weapon']},
    {name: 'знак старших богов', src: 'statics/items/eldritch_sign.jpg', type: ['item', 'magic']},
    {name: 'колдовской клинок', src: 'statics/items/enchanted_blade.jpg', type: ['item', 'magic', 'weapon']},
    {name: 'карта экспедиции', src: 'statics/items/expedition_map.jpg', type: ['trinket', 'book']},
    {name: 'дорогой костюм', src: 'statics/items/expensive_suit.png', type: ['item']},
    {name: 'рыболовная сеть', src: 'statics/items/fish_net.png', type: ['item']},
    {name: 'свежие фрукты', src: 'statics/items/fresh_fruit.jpg', type: ['item']},
    {name: 'аспирант', src: 'statics/items/graduate_student.jpg', type: ['ally']},
    {name: 'проводник', src: 'statics/items/guide.jpg', type: ['ally']},
    {name: 'взломщик', src: 'statics/items/hacker.jpg', type: ['ally']},
    {name: 'топор', src: 'statics/items/hatchet.jpg', type: ['item', 'weapon']},
    {name: 'наёмный громила', src: 'statics/items/hired_gunman.jpg', type: ['ally']},
    {name: 'священное копьё', src: 'statics/items/holy_lance.jpg', type: ['item', 'magic', 'weapon', 'relic']},
    {name: 'святая вода', src: 'statics/items/holy_water.jpg', type: ['item', 'magic']},
    {name: 'керосин', src: 'statics/items/kerosine.jpg', type: ['item']},
    {name: 'библия короля Якова', src: 'statics/items/king_jackobs_bible.jpg', type: ['item', 'book']},
    {name: 'фонарь', src: 'statics/items/lantern.jpg', type: ['item']},
    {name: 'исследователь из Ложи', src: 'statics/items/lodge_researcher.jpg', type: ['ally']},
    {name: 'счастливый портсигар', src: 'statics/items/lucky_cigarcase.png', type: ['trinket']},
    {name: 'кольцо-талисман', src: 'statics/items/lucky_ring.jpg', type: ['trinket']},
    {name: 'медицинская помощь', src: 'statics/items/med_help.png', type: ['service']},
    {name: 'медицинский журнал', src: 'statics/items/medical_diary.jpg', type: ['item', 'book']},
    {name: 'смотритель музея', src: 'statics/items/museum_curator.jpg', type: ['ally']},
    {name: 'таинственный фолиант', src: 'statics/items/mysterious_folio.jpg', type: ['item', 'book']},
    {name: 'волшебный клинок', src: 'statics/items/occult_blade.jpg', type: ['item', 'magic', 'weapon']},
    {name: 'оккультная книга', src: 'statics/items/occult_book.jpg', type: ['item', 'book']},
    {name: 'оккультный манускрипт', src: 'statics/items/occult_manuscript.png', type: ['item', 'book']},
    {name: 'ученый-оккультист', src: 'statics/items/ocultist_scientist.png', type: ['ally']},
    {name: 'тайный опус', src: 'statics/items/opus_arcana.jpg', type: ['item', 'book']},
    {name: 'личный помощник', src: 'statics/items/personal_assistant.jpg', type: ['ally']},
    {name: 'карманные часы', src: 'statics/items/pocket_watches.jpg', type: ['trinket']},
    {name: 'помощь полиции', src: 'statics/items/police_help.jpg', type: ['service']},
    {name: 'полицейский журнал', src: 'statics/items/police_reports.jpg', type: ['item']},
    {name: 'частный сыщик', src: 'statics/items/private_investigator.jpg', type: ['ally']},
    {name: 'защитный амулет', src: 'statics/items/protective_amulet.jpg', type: ['item']},
    {name: 'кроличья лапка', src: 'statics/items/rabbit_leg.png', type: ['trinket']},
    {name: 'радиосвязь', src: 'statics/items/radio_comm.png', type: ['service']},
    {name: 'доклад разведки', src: 'statics/items/reconnaissance_report.jpg', type: ['service']},
    {name: 'щедрое угощение', src: 'statics/items/rich_meal.jpg', type: ['service']},
    {name: 'ритульный кинжал', src: 'statics/items/ritual_dagger.jpg', type: ['item', 'magic', 'weapon']},
    {name: 'святилище', src: 'statics/items/sanctuary.jpg', type: ['service']},
    {name: 'тайный агент', src: 'statics/items/secret_agent.jpg', type: ['ally']},
    {name: 'шкатулка с секретом', src: 'statics/items/secret_box.jpg', type: ['trinket']},
    {name: 'служба доставки', src: 'statics/items/shipping_service.jpg', type: ['service']},
    {name: 'ритуал серебряных сумерек', src: 'statics/items/silver_twilight_ritual.jpg', type: ['service']},
    {name: 'знахарь', src: 'statics/items/sorcerer.jpg', type: ['ally']},
    {name: 'спецоперация', src: 'statics/items/special_operation.png', type: ['service']},
    {name: 'специальная подготовка', src: 'statics/items/specific_training.jpg', type: ['quest']},
    {name: 'агент мафии', src: 'statics/items/syndicate_representative.jpg', type: ['ally']},
    {name: 'слезоточивый газ', src: 'statics/items/tear_gas.jpg', type: ['item', 'weapon']},
    {name: 'ужасный талисман', src: 'statics/items/terrible_mascot.jpg', type: ['trinket']},
    {name: 'посланец Ватикана', src: 'statics/items/vatican_ambassador.jpg', type: ['ally']},
    {name: 'кнут', src: 'statics/items/whip.jpg', type: ['item', 'weapon']},
    {name: 'виски', src: 'statics/items/whiskey.jpg', type: ['item']},
    {name: 'набор отмычек', src: null, type: ['trinket']},
    {name: 'волшебник', src: null, type: ['ally']},
    {name: 'запретный текст', src: null, type: ['item', 'book']},
    {name: 'оккультный гримуар', src: null, type: ['item', 'book']},
    {name: 'наёмный убийца', src: null, type: ['ally']},
    {name: 'энциклопедия иных миров', src: null, type: ['item', 'book']},
    {name: 'полицейский рейд', src: null, type: ['service']},
    {name: 'гадание', src: null, type: ['service']},
    {name: 'колдовской лук', src: null, type: ['item', 'magic', 'weapon']},
    {name: 'вечерние курсы', src: null, type: ['service']},
    {name: 'фотоаппарат', src: null, type: ['item']},
    {name: 'дневник сновидений', src: null, type: ['item', 'book']},
    {name: 'своенравный аристократ', src: null, type: ['ally']},
    {name: 'алхимическое зелье', src: null, type: ['ally']},
    {name: 'шкатулка снов', src: null, type: ['trinket', 'magic']},
    {name: 'поиски правды', src: null, type: ['quest']},
  ],
  'artifacts': [
    {name: 'сумка пустоты', src: 'statics/artifacts/bag_of_void.jpg', type: ['item', 'magic']},
    {name: 'костяная свирель', src: 'statics/artifacts/bone_flute.jpg', type: ['item', 'magic']},
    {name: 'мозговой цилиндр ми-го', src: 'statics/artifacts/brain_cylinder.jpg', type: ['item', 'magic']},
    {name: 'Cultes des Goules', src: 'statics/artifacts/cultes.jpg', type: ['item', 'book']},
    {name: 'проклятая сфера', src: 'statics/artifacts/cursed_sphere.jpg', type: ['item', 'magic']},
    {name: 'De Vermis Mysteriis', src: 'statics/artifacts/de_vermis.jpg', type: ['item', 'book']},
    {name: 'идол-дракон', src: 'statics/artifacts/dragon_statue.jpg', type: ['item', 'magic', 'rare']},
    {name: 'эликсир жизни', src: 'statics/artifacts/elixir_of_life.jpg', type: ['item', 'elixir']},
    {name: 'причудливая статуя', src: 'statics/artifacts/fantastic_statue.jpg', type: ['item']},
    {name: 'флейта внешних богов', src: 'statics/artifacts/flute_of_gods.jpg', type: ['item', 'magic']},
    {name: 'шкатулка врат', src: 'statics/artifacts/gate_box.jpg', type: ['item', 'magic']},
    {name: 'хопеш из Бездны', src: 'statics/artifacts/groaning_abysses.jpg', type: ['item', 'magic', 'rare', 'weapon']},
    {name: 'меч святого Иеронима', src: 'statics/artifacts/holy_hieronymus_sword.jpg', type: ['item', 'magic', 'weapon']},
    {name: 'молниемёт', src: 'statics/artifacts/lightning_bolt.jpg', type: ['item', 'magic', 'weapon']},
    {name: 'реквием по Шаггаю', src: 'statics/artifacts/massa.jpg', type: ['item', 'book']},
    {name: 'стекло Мортлана', src: 'statics/artifacts/mortlans_glass.jpg', type: ['item', 'magic']},
    {name: 'Некрономикон', src: 'statics/artifacts/necronomicon.jpg', type: ['item', 'book']},
    {name: 'бледная маска', src: 'statics/artifacts/pale_mask.jpg', type: ['item', 'magic']},
    {name: "рубин Р'льеха", src: 'statics/artifacts/rliech_ruby.jpg', type: ['item', 'magic']},
    {name: 'молоко Шуб-Ниггурат', src: 'statics/artifacts/shub_milk.jpg', type: ['item', 'elixir']},
    {name: 'серебряный ключ', src: 'statics/artifacts/silver_key.jpg', type: ['item', 'magic']},
    {name: 'змеиная корона', src: 'statics/artifacts/snakes_crown.jpg', type: ['item', 'magic']},
    {name: "T'tka Halot", src: 'statics/artifacts/ttka_halot.jpg', type: ['item', 'book']},
    {name: 'маска стража', src: 'statics/artifacts/watchers_mask.jpg', type: ['item', 'magic']},
    {name: "меч Й'ха-Таллы", src: 'statics/artifacts/yhatalls_sword.jpg', type: ['item', 'magic', 'weapon']},
    {name: 'таблички Занту', src: 'statics/artifacts/zansus_tablets.jpg', type: ['item', 'book']},
    {name: 'кристаллизатор снов', src: null, type: ['item', 'magic']},
    {name: 'пентаграмма реальностей', src: null, type: ['item', 'magic']},
    {name: 'крест Цикраноша', src: null, type: ['item', 'magic']},
    {name: 'ключ Старших Богов', src: null, type: ['item', 'book']},
  ],
  'spells': [
    {name: 'астральное путешествие', src: 'statics/spells/astral_paths.jpg', type: ['aura']},
    {name: 'лазурное пламя', src: 'statics/spells/azure_flame.jpg', type: ['aura']},
    {name: 'ясновидение', src: 'statics/spells/clairvoyance.jpg', type: ['spell']},
    {name: 'сотворение', src: 'statics/spells/creation.jpg', type: ['ritual']},
    {name: 'иссушение', src: 'statics/spells/desiccation.jpg', type: ['ritual']},
    {name: 'защита плоти', src: 'statics/spells/flesh_protection.jpg', type: ['spell']},
    {name: 'пища для ума', src: 'statics/spells/food_for_thought.jpg', type: ['ritual']},
    {name: 'вселить отвагу', src: 'statics/spells/inspire_courage.jpg', type: ['spell']},
    {name: 'отметины Исиды', src: 'statics/spells/isis_marks.jpg', type: ['aura']},
    {name: 'благословение Исиды', src: 'statics/spells/isisa_blessing.jpg', type: ['ritual']},
    {name: 'лишение силы', src: 'statics/spells/loss_strength.jpg', type: ['spell']},
    {name: 'пронзить пустоту', src: 'statics/spells/pierce_void.jpg', type: ['ritual']},
    {name: 'ядовитый туман', src: 'statics/spells/poison_fog.jpg', type: ['ritual']},
    {name: 'туманы Релеха', src: 'statics/spells/releh_fogs.jpg', type: ['spell']},
    {name: 'голос Ра', src: 'statics/spells/voice_of_ra.jpg', type: ['aura']},
    {name: 'исцеляющие слова', src: 'statics/spells/words_of_comfort.jpg', type: ['spell']},
    {name: 'астральное путешествие', src: 'statics/spells/astral_paths.jpg', type: ['aura']},
    {name: 'найти врата', src: null, type: ['aura']},
    {name: 'жуткое проклятие', src: null, type: ['spell']},
    {name: 'призыв', src: null, type: ['ritual']},
  ],
  'conditions': [
    {name: 'амнезия', src: 'statics/conditions/amnesia.jpg', type: ['madness']},
    {name: 'проклятие', src: 'statics/conditions/curse.jpg', type: ['misfortune']},
    {name: 'галлюцинации', src: 'statics/conditions/hallucinations.jpg', type: ['madness']},
    {name: 'паранойя', src: 'statics/conditions/paranoia.jpg', type: ['madness']},
    {name: 'праведник', src: 'statics/conditions/righteousness.jpg', type: ['gift']},
    {name: 'благословение', src: null, type: ['gift']},
    {name: 'быстрое обучение', src: null, type: ['talent']},
    {name: 'отвага', src: null, type: ['talent']},
    {name: 'самообладание', src: null, type: ['gift', 'talent']},
    {name: 'боевой азарт', src: null, type: ['talent']},
    {name: 'неуловимость', src: null, type: ['talent']},
    {name: 'видения', src: null, type: ['talent']},
  ],
  'rareItems': [
    {name: 'древний меч', src: 'statics/rare_items/ancient_sword.jpg', type: ['item', 'rare', 'magic', 'weapon']},
    {name: 'Асенат Уэйт', src: 'statics/rare_items/asenat_wait.jpg', type: ['ally']},
    {name: 'Этьен-Лоран', src: 'statics/rare_items/etien_loran.jpg', type: ['ally']},
    {name: 'потерянное сокровище', src: 'statics/rare_items/lost_treasure.jpg', type: ['item', 'rare', 'magic']},
    {name: 'таинственный идол', src: 'statics/rare_items/mysterious_idol.jpg', type: ['item', 'rare', 'magic']},
    {name: 'молитва', src: 'statics/rare_items/prayer.jpg', type: ['quest']},
    {name: 'профессор Райс', src: 'statics/rare_items/prof_rise.jpg', type: ['ally']},
    {name: 'сдержать древних', src: 'statics/rare_items/seal_ancients.jpg', type: ['quest']},
    {name: 'каменный календарь', src: 'statics/rare_items/stone_calendar.jpg', type: ['item', 'rare', 'magic']},
    {name: 'каменный сундук', src: 'statics/rare_items/stone_chest.jpg', type: ['item', 'rare']},
    {name: 'каменная табличка', src: 'statics/rare_items/stone_tablet.jpg', type: ['item', 'rare']},
    {name: 'исследовать руины', src: 'statics/rare_items/trawl_ruins.jpg', type: ['quest']},
    {name: 'изучение пространств', src: null, type: ['quest']},
    {name: 'закопать поглубже', src: null, type: ['quest']},
    {name: 'пройти по лей-линиям', src: null, type: ['quest']},
    {name: 'энциклопедия мифа', src: null, type: ['item', 'book']},
    {name: 'туз мечей', src: null, type: ['trinket', 'taro']},
    {name: 'мистическое исследование', src: null, type: ['quest']},
    {name: 'четверка кубков', src: null, type: ['trinket', 'taro']},
    {name: 'Рэндольф Картер', src: null, type: ['ally']},
    {name: 'Бэзил Элтон', src: null, type: ['ally']},
    {name: 'стабилизатор потоков', src: null, type: ['item']},
    {name: 'Луна XVIII', src: null, type: ['trinket', 'taro']},
    {name: 'Смерть XIII', src: null, type: ['trinket', 'taro']},
    {name: 'мисс Дойл', src: null, type: ['ally']},
    {name: 'пятерка пентаклей', src: null, type: ['trinket', 'taro']},
  ]
};
